# Generated by Django 3.1.7 on 2021-03-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='other_cable_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='other_installer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='other_manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='other_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='other_strand_config',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='cable_type',
            field=models.CharField(choices=[('12', 'ADSS Mini-Span'), ('6', 'ADSS Medium'), ('6', 'ADSS Transmission'), ('6', 'UG Armored'), ('6', 'OPGW'), ('6', 'ABF'), ('other', 'Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cable',
            name='foot_stamp_units',
            field=models.CharField(choices=[('foot', 'Foot'), ('meter', 'Meter')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cable',
            name='infrastructure_class',
            field=models.CharField(choices=[('backbone', 'Backbone'), ('lateral', 'Lateral'), ('pigtail', 'Pigtail')], max_length=8),
        ),
        migrations.AlterField(
            model_name='cable',
            name='installer',
            field=models.CharField(choices=[('eweb', 'EWEB'), ('mfs', 'MFS'), ('astrotech', 'AstroTech'), ('other', 'Other')], max_length=9),
        ),
        migrations.AlterField(
            model_name='cable',
            name='manufacturer',
            field=models.CharField(choices=[('3m', '3M'), ('afl', 'AFL Telecom'), ('alcatel', 'Alcatel'), ('att', 'AT&T'), ('belde', 'Belde'), ('chromatic', 'Chromatic Tech'), ('draka', 'Draka USA'), ('ofs', 'OFS'), ('occ', 'Optical Cable Corp'), ('prysmian', 'Prysmian/Pirelli'), ('remmee', 'Remmee Products Corp'), ('other', 'Other')], max_length=9),
        ),
        migrations.AlterField(
            model_name='cable',
            name='owner',
            field=models.CharField(choices=[('eweb', 'EWEB'), ('city', 'City'), ('lcog', 'LCOG'), ('sub', 'SUB'), ('level3', 'LEVEL 3'), ('lsn', 'LSN'), ('other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='cable',
            name='strand_config',
            field=models.CharField(choices=[('12', 'Typical Tube Color Order – 12 strands/tube'), ('6', 'Typical Tube Color Order– 6 strands/tube'), ('other', 'Other')], max_length=5),
        ),
    ]
