# Generated by Django 3.1.7 on 2021-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0002_auto_20210323_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='cable_type',
            field=models.CharField(choices=[('ADSSMini', 'ADSS Mini-Span'), ('ADSSMedium', 'ADSS Medium'), ('ADSSTransmission', 'ADSS Transmission'), ('UGArmored', 'UG Armored'), ('OPGW', 'OPGW'), ('ABF', 'ABF'), ('other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='cable',
            name='installer',
            field=models.CharField(choices=[('EWEB', 'EWEB'), ('MFS', 'MFS'), ('astroTech', 'AstroTech'), ('other', 'Other')], max_length=9),
        ),
        migrations.AlterField(
            model_name='cable',
            name='manufacturer',
            field=models.CharField(choices=[('3M', '3M'), ('AFL', 'AFL Telecom'), ('alcatel', 'Alcatel'), ('ATT', 'AT&T'), ('belde', 'Belde'), ('chromatic', 'Chromatic Tech'), ('draka', 'Draka USA'), ('OFS', 'OFS'), ('OCC', 'Optical Cable Corp'), ('prysmian', 'Prysmian/Pirelli'), ('remmee', 'Remmee Products Corp'), ('other', 'Other')], max_length=9),
        ),
        migrations.AlterField(
            model_name='cable',
            name='owner',
            field=models.CharField(choices=[('EWEB', 'EWEB'), ('city', 'City'), ('LCOG', 'LCOG'), ('SUB', 'SUB'), ('level3', 'LEVEL 3'), ('LSN', 'LSN'), ('other', 'Other')], max_length=6),
        ),
    ]
