# Generated by Django 3.1.7 on 2021-03-23 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0003_auto_20210323_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime uploaded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime uploaded'),
            preserve_default=False,
        ),
    ]
