# Generated by Django 3.1.7 on 2021-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0004_auto_20210323_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='installation_type',
            field=models.CharField(choices=[('free', 'Free Standing'), ('wall', 'Wall Mount')], max_length=4),
        ),
        migrations.AlterField(
            model_name='panel',
            name='installer',
            field=models.CharField(choices=[('EWEB', 'EWEB'), ('MFS', 'MFS'), ('astroTech', 'AstroTech'), ('other', 'Other')], max_length=9),
        ),
        migrations.AlterField(
            model_name='panel',
            name='location_type',
            field=models.CharField(choices=[('indoors', 'Indoors'), ('outdoors', 'Outdoors')], max_length=8),
        ),
        migrations.AlterField(
            model_name='panel',
            name='model',
            field=models.CharField(choices=[('BJ-1346', 'BJ-1346'), ('CCH-04U', 'CCH-04U'), ('FDC-001', 'FDC-001'), ('FDC-002', 'FDC-002'), ('FDC-005F', 'FDC-005F'), ('FL2000', 'FL2000'), ('WDC-001', 'WDC-001'), ('WDC-002', 'WDC-002'), ('other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='panel',
            name='mount_type',
            field=models.CharField(choices=[('rack', 'Rack'), ('frame', 'Frame'), ('cabinet', 'Cabinet')], max_length=7),
        ),
        migrations.AlterField(
            model_name='panel',
            name='owner',
            field=models.CharField(choices=[('EWEB', 'EWEB'), ('4J', '4J SD'), ('bethel', 'Bethel SD'), ('ESD', 'Lane ESD'), ('LTD', 'LTD'), ('LCOG', 'LCOG'), ('eugene', 'City of Eugene'), ('springfield', 'City of Springfield'), ('lane', 'Lane County'), ('SUB', 'SUB'), ('level3', 'Level 3'), ('UO', 'U of O'), ('other', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='panel',
            name='port_type',
            field=models.CharField(choices=[('SC', 'SC'), ('LC', 'LC'), ('ST', 'ST'), ('other', 'Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='panel',
            name='slot_orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=10),
        ),
    ]
