# Generated by Django 3.1.7 on 2021-03-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0005_auto_20210323_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='other_installer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='other_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='other_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='other_port_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
