# Generated by Django 3.1.7 on 2021-03-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0006_auto_20210323_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
